export const TUTORIAL_TYPE = {
  HOME_PAGE: 'HOME_PAGE',
  WEB_EDITOR: 'WEB_EDITOR',
};
export const RWD_MODE = {
  DESKTOP: 'DESKTOP',
  MOBILE: 'MOBILE',
};
export const DEBOUND_TIME_SAVE_HISTORY = 300;
export const MAXIMUM_WEB_EDITOR_NAME = 50;
export const BREAK_POINT_MOBILE = 600;

export const MESSAGE_TYPES = {
  SUCCESS: 'success',
  ERROR: 'error',
  GUIDE: 'guide',
};
export const SIDE_BAR_ACTION = {
  CLICKED_SESSION: 'clicked_session',
  CLICKED_AI_TOOLS: 'clicked_ai_tools',
  CLICKED_CAPACITY: 'clicked_capacity',
};
export type MessageType = (typeof MESSAGE_TYPES)[keyof typeof MESSAGE_TYPES];
export const MAX_HISTORY_EDITOR = 20;

export const METRICS_KEY = {
  PLAN_NAME: 'PLAN_NAME',
  PROJECTS_CREATED: 'PROJECTS_CREATED',
  PROJECTS_PUBLISHED: 'PROJECTS_PUBLISHED',
  TOTAL_CAPACITY: 'TOTAL_CAPACITY',
  TOTAL_CAPACITY_USED: 'TOTAL_CAPACITY_USED',
  TOTAL_PROJECT: 'TOTAL_PROJECT',
  TOTAL_CAPACITY_USED_IN_PROJECT: 'TOTAL_CAPACITY_USED_IN_PROJECT',
};
export const THRESH_HOLD = 0.75;
