export const KEY_LOCAL_STORAGE = {
  IS_AUTHENTICATED: 'IS_AUTHENTICATED',
  INFO_USER: 'INFO_USER',
  I18N_LANGUAGE: 'vyin-ai-language',
  TOKEN_TEMPORARY: 'TOKEN_TEMPORARY',
  TOKEN_TENANT: 'TOKEN_TENANT',
  VERSION_CHANGE: 'VERSION_CHANGE',
  ID_REFRESH_SESSION_ID: 'ID_REFRESH_SSID',
};
export const STEP_UPDATE = {
  INPUT_NAME_AND_TEL: 1,
  VIEW_NICKNAME_AND_AVATAR: 2,
};
export const STEP_CREATE_TENANT = {
  INPUT_INFO_COMPANY: 1,
  INPUT_NAME_TENANT: 2,
};
export const ERROR_CODE = {
  OTP_VERIFICATION_EXCEED_LIMIT: 'OTP_VERIFICATION_EXCEED_LIMIT',
  LD_INVALID_PROJECT_SETTINGS: 'LD_INVALID_PROJECT_SETTINGS',
};

export const ROLES = {
  SYSTEM_ADMIN: 'system_admin',
  SYSTEM_EDITOR: 'system_editor',
  SYSTEM_VIEWER: 'system_viewer',
  TENANT_OWNER: 'tenant_owner',
  TENANT_ADMIN: 'tenant_admin',
  TENANT_ASSISTANT_ADMIN: 'tenant_assistant_admin',
  TENANT_USER: 'tenant_user',
  APP_EDITOR: 'app_editor',
  APP_VIEWER: 'app_viewer',
};
export const CHECK_ROLES = {
  [ROLES.APP_EDITOR]: 2,
  [ROLES.APP_VIEWER]: 1,
  [ROLES.SYSTEM_ADMIN]: 3,
  [ROLES.SYSTEM_EDITOR]: 2,
  [ROLES.SYSTEM_VIEWER]: 1,
  [ROLES.TENANT_OWNER]: 4,
  [ROLES.TENANT_ADMIN]: 3,
  [ROLES.TENANT_ASSISTANT_ADMIN]: 2,
  [ROLES.TENANT_USER]: 1,
};

export const HTTP_ERRORS = {
  // 4xx Client Errors
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  PAYMENT_REQUIRED: 402,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  NOT_ACCEPTABLE: 406,
  PROXY_AUTHENTICATION_REQUIRED: 407,
  REQUEST_TIMEOUT: 408,
  CONFLICT: 409,
  GONE: 410,
  LENGTH_REQUIRED: 411,
  PRECONDITION_FAILED: 412,
  PAYLOAD_TOO_LARGE: 413,
  URI_TOO_LONG: 414,
  UNSUPPORTED_MEDIA_TYPE: 415,
  RANGE_NOT_SATISFIABLE: 416,
  EXPECTATION_FAILED: 417,
  MISDIRECTED_REQUEST: 421,
  UNPROCESSABLE_ENTITY: 422,
  LOCKED: 423,
  FAILED_DEPENDENCY: 424,
  TOO_EARLY: 425,
  UPGRADE_REQUIRED: 426,
  PRECONDITION_REQUIRED: 428,
  TOO_MANY_REQUESTS: 429,
  REQUEST_HEADER_FIELDS_TOO_LARGE: 431,
  UNAVAILABLE_FOR_LEGAL_REASONS: 451,

  // 5xx Server Errors
  INTERNAL_SERVER_ERROR: 500,
  NOT_IMPLEMENTED: 501,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
  HTTP_VERSION_NOT_SUPPORTED: 505,
  VARIANT_ALSO_NEGOTIATES: 506,
  INSUFFICIENT_STORAGE: 507,
  LOOP_DETECTED: 508,
  NOT_EXTENDED: 510,
  NETWORK_AUTHENTICATION_REQUIRED: 511,
};

export const TYPE_CHECK_LIMIT = {
  TENANT_USER: 'TENANT_USER',
};
